# fastkart e-com full project from : https://github.com/yasirmahabub/FastKart-E-Commerce
# erd: https://drawsql.app/teams/personal-2601/diagrams/single-vendor-e-commerce-project

"""
Django settings for fastkart project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2e0&)5^w3yfoyr36v^is3+ihc7)n(*s=0wu$f)5f_$cp^u5t+q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	"accounts",
	"products",
	"carts",
	"orders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fastkart.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

print("base dir = ", BASE_DIR) #
TEMPLATES = [ #
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
		#'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                #"carts.context_processors.counter", # see context_processors.py in main github
				'carts.context_processors.cart_context',  # Add this line
            ],
        },
    },
]

WSGI_APPLICATION = 'fastkart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "staticfiles"),] #

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

###########################################################################################################
import certifi
import ssl

AUTH_USER_MODEL = "accounts.CustomUser"

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" # ---
#EMAIL_BACKEND = "accounts.backends.custom_backend.CustomBackend"
#EMAIL_BACKEND = "accounts.backends.custom_backend.LenientSMTPBackend"
EMAIL_HOST = "smtp.gmail.com" # commonly used for development, for production use aws, sandgrid etc email service
# Recommended Gmail SMTP Settings for Django
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_PORT = 465 # older
#EMAIL_USE_SSL = True


import environ
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="user@example.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
# print(env("EMAIL_HOST_USER"))

#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER #
DEFAULT_FROM_EMAIL = "fastkart app"

"""
google app passwords: -- at 1:06:00 of video class 2
anup30coc@gmail.com
app: fastkart
pw: "in .env file"
"""

"""
app account:
email - anupbarua30@gmail.com
pw: mpfastkart
"""


# chechout: https://pypi.org/project/Django-Verify-Email/

AUTHENTICATION_BACKENDS = [
    "accounts.authentication.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",  # with multiple backends, problem while resetting password. but without it cant login to admin panel.
]

DELIVERY_CHARGE = env.int("DELIVERY_CHARGE", default=0)

SSLCOMMERZ_IS_SANDBOX = env.bool("SSLCOMMERZ_IS_SANDBOX")
SSLCOMMERZ_STORE_ID    = env("SSLCOMMERZ_STORE_ID")
SSLCOMMERZ_STORE_PASS  = env("SSLCOMMERZ_STORE_PASS")
