# Generated by Django 5.2 on 2025-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_user_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
